### ISSUE TITLE
Help Appwrite upgrade to GitHub issue forms ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/sdk-generator#268]
# Introduction

GitHub has recently started public beta for GitHub repositories regarding the new issue forms feature. This feature lets you create interactive issue requests and validate them 🤯

Your task is to create **GitHub issue forms** for this repository. Please use [Appwrite's issue templates](https://github.com/appwrite/appwrite/tree/master/.github/ISSUE_TEMPLATE) as a source of template for this PR.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Prepare **bug report** issue form in `.github/ISSUE_TEMPLATE/bug.yaml`
- [ ] Prepare **documentation** issue form in `.github/ISSUE_TEMPLATE/documentation.yaml`
- [ ] Prepare **feature request** issue form in `.github/ISSUE_TEMPLATE/feature.yaml`
- [ ] Push changes to your **master** and test issue forms on your fork
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by aadityamp01** [comment]
Hello, I am interested to work on this issue!
Thank you!

**Comment by Meldiron** [comment]
Whoops, I created a duplicate. Let's move all activity to new one: https://github.com/appwrite/sdk-generator/issues/269

Also, please wait to October before asking for assigning to Hacktoberfest-labeled issues 😊
