### ISSUE TITLE
🚀 Feature: Constants for Error Types

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/sdk-generator#698]
### 🔖 Feature description

For the error types exposed [here](https://appwrite.io/docs/response-codes#errorTypes) we should have a class with constants or an enum so we don't have to manually put the string in the code.

### 🎤 Pitch

Let say I want to display some error message specifically to the user depending on the type, so instead of doing this:

```dart
AppWriteException exception;
if (exception.type == 'user_already_exists') {
...
}
```

I could use the constant instead
```dart
AppWriteException exception;

if (exception.type == ErrorType.userAlreadyExists) {
...
}
```

### Requirements

To implement this, we'll need to update the API specs to include the error types. For the API specs, we'll want to add an `AppwriteException` schema/definition like so:

```json
    "definitions": {
        "appwriteException": {
            "properties": {
                "message": {
                    "type": "string",
                    "description": "Error message.",
                    "x-example": "Invalid id: Parameter must be a valid number"
                },
                "type": {
                    "type": "string",
                    "description": "Error type.",
                    "enum": [
                        "general_mock",
                        "general_argument_invalid"
                    ],
                    "x-example": "argument_invalid"
                },
                "code": {
                    "type": "integer",
                    "description": "Error code.",
                    "x-example": 400,
                    "format": "int32"
                }
            },
            "x-appwrite": {
                "types": [
                    {
                        "code": 400,
                        "type": "general_mock",
                        "description": "General errors thrown by the mock controller used for testing."
                    },
                    {
                        "code": 400,
                        "type": "general_argument_invalid",
                        "description": "The request contains one or more invalid arguments. Please refer to the endpoint documentation."
                    }
                ]
            }
        },
        "any": {
            "description": "Any",
            "type": "object",
            "additionalProperties": true
        },
```

Note: 

1. this is an example for Swagger 2. The equivalent will need to be done for OpenAPI 3
2. we're still finalizing whether was want the types in `definitions.appwriteException` or `definitions.appwriteException.properties.types`

The SDK Generator should use the API specs to generate the enums with descriptions like:

```javascript
enum ErrorType {
   /**
    * General errors thrown by the mock controller used for testing.
    */
    GeneralMock = "general_mock",

    /**
     * The request contains one or more invalid arguments. Please refer to the endpoint documentation.
     */
   GeneralArgumentInvalid = "general_argument_invalid"
}
```

```dart
enum ErrorType implements Comparable<ErrorType> {
  /// General errors thrown by the mock controller used for testing.
  generalMock(code: 400, type: 'general_mock'),
  /// General errors thrown by the mock controller used for testing.
  generalArgumentInvalid(code: 400, type: 'general_argument_invalid');

  const ErrorType({
    required this.code,
    required this.type,
  });

  final int code;
  final String type;

  @override
  int compareTo(ErrorType other) => type.compareTo(other.type);
}
```

So that the developer's IDE will show the description like:

<img width="610" alt="image" src="https://github.com/appwrite/sdk-generator/assets/1477010/8ffb1c3e-4490-4006-af1b-1dd87781a77a">

### Tasks

- [ ] Update Specs to include AppwriteException with the enum for types
- [ ] android
- [x] cli - not needed
- [ ] dart
- [ ] deno
- [ ] dotnet
- [ ] https://github.com/appwrite/sdk-for-flutter/issues/149
- [x] go - not ready
- [x] graphql/docs - not needed
- [ ] kotlin
- [ ] node
- [ ] php
- [ ] python
- [x] rest/docs - not needed
- [ ] ruby
- [ ] swift
- [ ] web

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by sahilsaha7773** [comment]
Hey @stnguyen90, I and @goswamianshuman are working on this, could you please assign it to us?

**Comment by goswamianshuman** [comment]
Hey @stnguyen90, we are here now you can assign this PR to us.😄

**Comment by 35C4n0r** [comment]
@Haimantika I would like to work on this Issue.

**Comment by Haimantika** [comment]
> @Haimantika I would like to work on this Issue.

Hi @35C4n0r have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by monhelnog** [comment]
I would like to work on this issue

**Comment by Haimantika** [comment]
> I would like to work on this issue

Hi, we are assigning issues on a first-come, first-serve basis, if @35C4n0r  is decides to drop off, we will assign it to you.

**Comment by heyhimansh** [comment]
Hey @Haimantika, i would like to work on this issue.

**Comment by Haimantika** [comment]
> Hey @Haimantika, i would like to work on this issue.

Hi, we are assigning issues on a first-come, first-serve basis, if @35C4n0r decides to drop off, we will assign it to you.

**Comment by Haimantika** [comment]
Hi @35C4n0r is there an update? The issue will be assigned to the next person in line soon due to inactivity

**Comment by 35C4n0r** [comment]
Hi @Haimantika working on this, i've managed to understand the codebase, am still working on this issue.

**Comment by 35C4n0r** [comment]
@stnguyen90 @Haimantika 
the URL for the Swagger API Spec is invalid https://github.com/appwrite/sdk-generator/blob/2069238e3a3b96ebf6359e8eca8caf4e37a1868c/README.md?plain=1#L50
Can you please inform me about the correct URL.

**Comment by 35C4n0r** [comment]
@stnguyen90 should we put the enum in exceptions.*.twig or create a new file for it.
Also for the spec you provided this is the only part we should make an enum out of right?
```
"x-appwrite": {
                "types": [
                    {
                        "code": 400,
                        "type": "general_mock",
                        "description": "General errors thrown by the mock controller used for testing."
                    },
                    {
                        "code": 400,
                        "type": "general_argument_invalid",
                        "description": "The request contains one or more invalid arguments. Please refer to the endpoint documentation."
                    }
                ]
            }
        }
```

**Comment by stnguyen90** [comment]
@35C4n0r, 

> the URL for the Swagger API Spec is invalid

The specs are [here](https://github.com/appwrite/appwrite/tree/main/app/config/specs).

> should we put the enum in exceptions.*.twig or create a new file for it.

In the exception file is fine.

> Also for the spec you provided this is the only part we should make an enum out of right?

FYI, we already have https://github.com/appwrite/appwrite/pull/5979 open for the specs part, although we haven't finalized where in the specs the types should go.

**Comment by ItzNotABug** [comment]
Commenting to get notified of any updates to this!

**Comment by ChiragAgg5k** [comment]
Before this can be implemented in the generator, we need an authoritative error catalog and a defined representation in the API specification.

Could a maintainer confirm:

- where the canonical error names, HTTP codes, and descriptions now live;
- the current status or replacement for appwrite/appwrite#5979;
- how the error catalog should be represented in the specification; and
- the intended generated API for each SDK (constants, enums, or typed exceptions)?

Once that contract is established upstream, the per-language generation work can be scoped here.
